---
# tasks file for bashrc
- name: insert/update an extention of ~/.bashrc to point to ~/.bash_supplement
  blockinfile:
    path: ~/.bashrc
    block: |
      if [[ -f ~/.bash_supplement ]]; then
        . ~/.bash_supplement
      fi
- name: Create a supplement bash files
  copy:
    src: {{ item.src }}
    dest: {{ item.dst }}
    mode: '0644'
  with_items:
  - { src: bash_aliases, dst: ~/.bash_aliases }
  - { src: bash_functions , dst: ~/.bash_functions }
  - { src: bash_supplement, dst: ~/.bash_supplement }

